### ISSUE TITLE
出现如下报错信息如何解决？

### ISSUE THREAD

**Issue by github-ljx** [Amazingwujun/mqttx#10]
Exception in thread "pool-1-thread-1" java.lang.IllegalArgumentException: messageId: 503316480 (expected: 1 ~ 65535)
	at io.netty.handler.codec.mqtt.MqttMessageIdVariableHeader.from(MqttMessageIdVariableHeader.java:31)
	at com.jun.mqttx.broker.handler.ConnectHandler.lambda$republish$5(ConnectHandler.java:290)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.jun.mqttx.broker.handler.ConnectHandler.republish(ConnectHandler.java:286)
	at com.jun.mqttx.broker.handler.ConnectHandler.lambda$process0$3(ConnectHandler.java:253)
	at com.jun.mqttx.utils.GlobalExecutor$DefaultTask.run(GlobalExecutor.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Amazingwujun** [comment]
此为代码 bug ，稍后修复

**Comment by Amazingwujun** [comment]
拉取最新 v1.0 代码试试

**Comment by github-ljx** [comment]
好的，谢谢，我待会试一下，还有一个问题是：当我使用客户端发布完20个消息后，就不能继续发布了，然后服务器端会报 心跳超时，这是怎么回事呀？

**Comment by Amazingwujun** [comment]
你可以先使用 [mqttfx](https://mqttfx.jensd.de/index.php/download) 这款软件测试一下，判断客户端还是服务端的问题，再细化描述问题给我。或者给出复现步骤，否则根据你的描述我无法判断问题出在哪里。

**Comment by github-ljx** [comment]
嗯嗯，好的，应该是我这边写的客户端代码有问题。
